name: CI

# we can specify what GitHub events trigger the action
on: push

jobs:

  build:

    # we can specify the OS
    runs-on: ubuntu-latest

    # a job is a series of steps
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name Set up Python 3.11
       uses: actions/setup-python@v5
       with:
        python-version: "3.11"

    - name: Install Python dependencies
      run: |
       python3 -m pip install --upgrade pip
       python3 -m pip install -r requirements.txt

    - name: Test with PyTest
      run: |
       python3 -m pytest --cov=inflammation.models

